# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Template.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ipAddress = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ipAddress.setGeometry(QtCore.QRect(10, 10, 131, 31))
        self.ipAddress.setObjectName("ipAddress")
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setGeometry(QtCore.QRect(30, 50, 93, 28))
        self.connectButton.setObjectName("connectButton")
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setGeometry(QtCore.QRect(10, 490, 171, 41))
        self.runButton.setObjectName("runButton")
        self.xValue = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.xValue.setGeometry(QtCore.QRect(10, 110, 131, 31))
        self.xValue.setObjectName("xValue")
        self.setXButton = QtWidgets.QPushButton(self.centralwidget)
        self.setXButton.setGeometry(QtCore.QRect(30, 150, 93, 28))
        self.setXButton.setObjectName("setXButton")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 437, 171, 41))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ipAddress.setPlainText(_translate("MainWindow", "192.168.1.100"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.xValue.setPlainText(_translate("MainWindow", "0"))
        self.setXButton.setText(_translate("MainWindow", "Set X"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
